version: '3.8'
services:
  mobofarm_simulation:
    image: mobosim:latest
    container_name: mobosim
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./tmp/docker.xauth:/tmp/.docker.xauth:rw
      - ../:/workspace
      - ../simulations/gazebo_models:/home/ros/.gazebo/models
    devices:
      - "/dev/nvidia0:/dev/nvidia0"
      - "/dev/nvidiactl:/dev/nvidiactl"
      - "/dev/nvidia-uvm:/dev/nvidia-uvm"
      - "/dev/dri/card0:/dev/dri/card0"
    runtime: nvidia
    command: bash
    network_mode: host
    privileged: true
    security_opt:
      - seccomp:unconfined
    user: ros
    stdin_open: true  # Keep stdin open
    tty: true         # Allocate a pseudo-TTY
